### PR TITLE
Search bar

### PR DESCRIPTION
**Pull request by justinbgent**
Correctly switches fragments upon selecting the search bar and saves submitted search queries

- [x] New feature (non-breaking change which adds functionality)
- [x] Complete, tested, ready to review and merge
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by heiligbasil** [comment]
Getting 2 warnings:
1. [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
2. Parameter 'view' is never used, could be renamed to _

**Comment by justinbgent** [comment]
Both warnings are cleared

**Review by TylerBerrett — APPROVED** [review]
Love the clean architecture especially the code for the recycler view in the home fragment how you added them to view model. Also really like the hide and show keyboard functions

**Review by heiligbasil — APPROVED** [review]
2 issues. Search bar shifts slightly to the left when initially activated. And duplicate search terms can be added. Both should be easy to fix and shouldn't prevent this merge.

**Pull request merged**
