### PR TITLE
Initialize project in android studio

### PR DESCRIPTION
**Pull request by justinbgent**
# Description
Initial project.

Fixes # Start Project

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

## Change Status

- [x ] Complete, tested, ready to review and merge

# Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts

### CODE REVIEW

**Comment by justinbgent** [comment]
This is an empty project for us to have a starting place

**Comment by heiligbasil** [comment]
Tested locally - looks good

**Review by heiligbasil — APPROVED** [review]
Cloned your PR to my local computer and verified it works

**Comment by TylerBerrett** [comment]
looks good

**Review by TylerBerrett — APPROVED** [review]
looks good

**Pull request merged**
