### PR TITLE
Dependency injection

### PR DESCRIPTION
**Pull request by justinbgent**
# Description

Add dependency injection with Koin, fix code to work smoother by moving the searchView out of MainActivity UI and injected it into HomeFragment and SearchFragment. Made cancel button live in SearchFragment only.

## Type of change

Add dependency injection.

## Change Status

- [x] Complete, but not tested (may need new tests)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] There are no merge conflicts

### CODE REVIEW

**Review by heiligbasil — DISMISSED** [review]
Way to go with Dependency Injection using Koin. The changes are working for me. One thing we'll want to look at is if we want the SearchViews in all of the locations to look the same.

**Comment by justinbgent** [comment]
I was able to make a commit to resolve the search switching sizes and it shouldn't be cut off anymore on any devices.

**Comment by heiligbasil** [comment]
1. The search bar is visually better! I notice it shifts down and to the right slightly when moving from the home fragment to the search fragment
2. Remove the unnecessary code from the strings.xml file (the Hello blank fragment line)
3. Move the poppins_regular.ttf file from the assets folder back into the font folder

**Comment by justinbgent** [comment]
SearchBar position is static, the assets folder has a duplicate file of the poppins_regular.ttf and the font folder already contained it.

**Review by TylerBerrett — APPROVED** [review]
love the DI good job

**Review by heiligbasil — APPROVED** [review]
The search bar is working now. Nice job

**Pull request merged**
