### PR TITLE
android:name set in manifest to the App class

### PR DESCRIPTION
**Pull request by justinbgent**
Fixes #
lateinit shared preferences is now initialized with android:name being set in manifest

### CODE REVIEW

**Review by heiligbasil — APPROVED** [review]
Runs fine...looks good

**Comment by justinbgent** [comment]
Made one more commit to smooth out threading issues

**Comment by heiligbasil** [comment]
New change allows the app to login

**Review by TylerBerrett — APPROVED** [review]
runs great glad you got Auth0 and Shared prefs working

**Pull request merged**
